package com.medibridge.user_service_medibridge.api.dto.request;

import com.medibridge.user_service_medibridge.util.constant.Gender;
import com.medibridge.user_service_medibridge.util.constant.Specialization;
import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

/**
 * Request DTO for creating doctor profile.
 * 
 * Security: Only ADMIN can create doctors
 * Compliance: Requires medical license and credentials
 * 
 * NOTE: Username and password are automatically generated by the system
 * during the secure onboarding process. Admin does not provide these fields.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreateDoctorRequest {

    // Email (used for credential generation and notifications)
    @NotBlank(message = "Email is required")
    @Email(message = "Email must be valid")
    private String email;

    // Personal information
    @NotBlank(message = "First name is required")
    private String firstName;

    private String middleName;

    @NotBlank(message = "Last name is required")
    private String lastName;

    @NotNull(message = "Date of birth is required")
    @Past(message = "Date of birth must be in the past")
    private LocalDate dateOfBirth;

    @NotNull(message = "Gender is required")
    private Gender gender;

    @NotBlank(message = "Phone number is required")
    @Pattern(regexp = "^[+]?[0-9]{10,15}$", message = "Phone number must be valid")
    private String phoneNumber;

    // Medical credentials
    @NotBlank(message = "Medical license number is required")
    private String medicalLicenseNumber;

    @NotBlank(message = "License issuing authority is required")
    private String medicalLicenseIssuingAuthority;

    @NotNull(message = "License issue date is required")
    @Past(message = "License issue date must be in the past")
    private LocalDate medicalLicenseIssueDate;

    @NotNull(message = "License expiry date is required")
    @Future(message = "License expiry date must be in the future")
    private LocalDate medicalLicenseExpiryDate;

    private String medicalRegistrationNumber;

    private String medicalCouncil;

    // Education
    @NotBlank(message = "Medical degree is required")
    private String medicalDegree;

    @NotBlank(message = "Medical school is required")
    private String medicalSchool;

    @NotNull(message = "Graduation year is required")
    @Min(value = 1950, message = "Graduation year must be after 1950")
    @Max(value = 2030, message = "Graduation year must be before 2030")
    private Integer graduationYear;

    private String additionalQualifications;

    // Specialization
    @NotNull(message = "Specialization is required")
    private Specialization specialization;

    private String subSpecialization;

    @NotNull(message = "Years of experience is required")
    @Min(value = 0, message = "Years of experience cannot be negative")
    private Integer yearsOfExperience;

    // Employment
    @NotBlank(message = "Department is required")
    private String department;

    @NotBlank(message = "Designation is required")
    private String designation;

    @NotBlank(message = "Employment type is required")
    private String employmentType;

    @NotNull(message = "Joining date is required")
    private LocalDate joiningDate;

    private String employeeId;

    private Double consultationFee;
}
